app: hmd-golang-challenge
service: hmd-golang-challenge

frameworkVersion: "3"

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: go1.x
  environment:
    DYNAMODB_TABLE: "hamid_devices"
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:us-east-1:*:table/hamid_devices"

functions:
  create:
    handler: /bin/go-challenge
    package:
      include:
        - ./bin/go-challenge
    events:
      - http:
          path: api/devices
          method: post
          cors: true

  get:
    handler: /bin/go-challenge
    package:
      include:
        - ./bin/go-challenge
    events:
      - http:
          path: api/devices/{id}
          method: get
          cors: true
 
 
resources:
  Resources:
    TodosDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName:  "hamid_devices"
